# Generated by Django 3.0.5 on 2020-04-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=480)),
                ('photo_url', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=60)),
                ('group_description', models.CharField(max_length=240)),
                ('public', models.BooleanField(default=True)),
                ('individual_invites', models.ManyToManyField(related_name='group_invites', to='socdist_app.User')),
                ('members', models.ManyToManyField(related_name='member_groups', to='socdist_app.User')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='socdist_app.User')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=60)),
                ('event_description', models.CharField(max_length=240)),
                ('event_img_url', models.CharField(max_length=240)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('group_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='socdist_app.Group')),
                ('individual_invites', models.ManyToManyField(related_name='event_invites', to='socdist_app.User')),
                ('members', models.ManyToManyField(related_name='member_events', to='socdist_app.User')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_events', to='socdist_app.User')),
            ],
            options={
                'ordering': ['event_name'],
            },
        ),
    ]
