# Generated by Django 3.0.5 on 2020-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socdist_app', '0002_auto_20200407_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_img_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(related_name='events', to='socdist_app.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='socdist_app.User'),
        ),
    ]
